# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build debug and test APK for screenshots"
  lane :cleanAssembleDebugTest do
    gradle(
      task: 'clean'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  desc "Build debug and test APK for screenshots"
  lane :assembleDebugTest do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
  end

  lane :screenshots do
    capture_android_screenshots()
  end

  desc "Upload a build to Play Store internal testing track"
  lane :internal do
    gradle(task: "clean assembleRelease")
    upload_to_play_store(
        track: 'internal',
        release_status: 'draft',
        skip_upload_aab: 'true',
        skip_upload_metadata: 'true',
        skip_upload_changelogs: 'true',
        skip_upload_images: 'true',
        skip_upload_screenshots: 'true',
    )
  
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
